### ISSUE TITLE
Is there a gitter or way to ask questions?

### ISSUE THREAD

**Issue by skedlukecollier** [typelevel/fabric#142]
Hello! 

Was giving this a go and wanted to ask some things, but found I couldn't access the gitter  
<img width="486" alt="Screenshot 2023-03-20 at 21 24 57" src="https://user-images.githubusercontent.com/112550264/226469580-60d83ada-07bf-497b-ac43-e39f700fc261.png">

**Comment by darkfrog26** [comment]
Feel free to ask questions here.
