### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by padhia** [typelevel/fabric#278]
I started using this library not too long ago, and so far, I really like it. I hope it gets regular support and updates.  

Is there any documentation besides the README that I missed? I was trying to figure out how to integrate custom types for JSON parsing, but I didn't find any documentation. I can study the source code and figure it out, but having a few quick recipes to follow would make it easier!

Thanks again for creating this library.

**Comment by padhia** [comment]
No worries at all. I do understand, and appreciate, the fact that you are sharing your voluntary work with the rest of us.

Part of the problem might be my lack of proficiency in Scala, so apologies in advance for asking some very basic questions. 

1. I am sure it's simple, but I was struggling to create a RW typeclass instance to parse JSON Str value into an instance of `java.util.UUID`; preferably, from an existing typeclass (similar to Circe's [contramap](https://circe.github.io/circe/codecs/custom-codecs.html#custom-encoders-decoders) to create a new typeclass for `UUID`.
2. Is it possible to create a custom Key type like [Circe's](https://circe.github.io/circe/codecs/custom-codecs.html#custom-key-types)?
3. I was able to create a parser for TOML by basing it on very easy-to-understand, `JacksonParser` code. Would it be possible to include TOML as one of the provided parsers, since Jackson already [supports it](https://github.com/FasterXML/jackson-dataformats-text/tree/2.19/toml)?

Thank you!

PS: I realize that these kinds of questions are better answered in support forums. If there is a forum where you or other friendly people answer such questions, please let me know.

**Comment by darkfrog26** [comment]
There are a lot of convenience features on `RW` to help with this sort of thing. For your case, it sounds like you can use `RW.string` to do what you want. Take a look at this implicit for a `FiniteDuration` to/from String: https://github.com/typelevel/fabric/blob/16fd0346e9b14b7d9cd705a09c8ea96e743233e1/core/shared/src/main/scala/fabric/rw/RWImplicits.scala#L52-L59

**Comment by padhia** [comment]
Thank you! Very simple and elegant!  I should have looked a bit more to have stumbled on this.

**Comment by darkfrog26** [comment]
No worries, I'm glad you're sorted out.
